### ISSUE TITLE
Feature Request: Would it be possible for this package to be made available through anaconda/ conda-forge?

### ISSUE THREAD

**Issue by saguerraty** [vcdi/ratemate#1]
Hi!
Would it be possible to add this package to the conda forge channel for use with [conda-forge?`](https://conda-forge.org/#add_recipe)
:) please

**Comment by datwiz** [comment]
No objections - thanks for the link.
We'll add this to our TODO list.

**Comment by saguerraty** [comment]
THX! :D

**Comment by djrobstep** [comment]
There is now a PR created to add this to conda-forge: https://github.com/conda-forge/staged-recipes/pull/15296

**Comment by datwiz** [comment]
Looks like the PR has been accepted and now available on conda-forge.

Closing the issue.
